using System;
using UnityEngine;
using UnityEngine.UI;

public class WindSlider : MonoBehaviour
{
    public WindSettings windSettings; // The ScriptableObject containing wind properties
    public Slider slider;             // The slider UI component

    public WindProperty propertyToControl = WindProperty.Speed; // Selectable property

    void Start()
    {
        Debug.Log("Initializing WindSlider...");

        if (slider == null)
        {
            slider = GetComponent<Slider>();
            if (slider == null)
            {
                Debug.LogWarning("No slider found. Creating one dynamically.");
                EnsureCanvasAndSlider();
            }
        }

        // Subscribe to WindManager updates
        WindManager.Instance.OnWindSettingsChanged += SyncSliderWithWindSettings;
        // Initialize slider value based on the selected property
        SyncSliderWithWindSettings(WindManager.Instance.currentWindSettings);

        // Add listener to handle slider changes
        slider.onValueChanged.AddListener(UpdateWindProperty);
    }


    private void OnDestroy()
    {
        if (null == WindManager.Instance)
        {
            return;
        }
        WindManager.Instance.OnWindSettingsChanged -= SyncSliderWithWindSettings;
    }
    public void SyncSliderWithWindSettings(WindSettings newWindSettings)
    {
        if (newWindSettings == null)
        {
            Debug.LogError("No wind settings assigned to slider");
            return;
        }
        windSettings = newWindSettings;

        float currentValue = slider.value; // Preserve slider's current value

        switch (propertyToControl)
        {
            case WindProperty.Speed:
                slider.minValue = windSettings.minWindSpeed;
                slider.maxValue = windSettings.maxWindSpeed;
                slider.value = Mathf.Clamp(currentValue, windSettings.minWindSpeed, windSettings.maxWindSpeed);
                Debug.Log($"Syncing Speed: min={windSettings.minWindSpeed}, max={windSettings.maxWindSpeed}, current={slider.value}");
                break;

            case WindProperty.Turbulence:
                slider.minValue = windSettings.minTurbulence;
                slider.maxValue = windSettings.maxTurbulence;
                slider.value = Mathf.Clamp(currentValue, windSettings.minTurbulence, windSettings.maxTurbulence);
                Debug.Log($"Syncing Turbulence: min={windSettings.minTurbulence}, max={windSettings.maxTurbulence}, current={slider.value}");
                break;

            case WindProperty.Interval:
                slider.value = WindManager.Instance.windChangeInterval;
                Debug.Log($"Syncing Interval: current={slider.value}");
                break;

            default:
                Debug.LogError("Invalid property");
                break;
        }
    }

    void UpdateWindProperty(float value)
    {
        windSettings = WindManager.Instance.currentWindSettings;
        switch (propertyToControl)
        {
            case WindProperty.Speed:
                windSettings.SetWindSpeed(value);
                break;

            case WindProperty.Turbulence:
                windSettings.SetTurbulenceValue(value);
                //Debug.Log($"Updated turbulence to {value}");
                break;

            case WindProperty.Interval:
                WindManager.Instance.SetWindChangeInterval(value);
                break;
        }
    }

    void EnsureCanvasAndSlider()
    {
        Canvas canvas = FindObjectOfType<Canvas>();
        if (canvas == null)
        {
            Debug.Log("No Canvas found! Creating a new one.");
            canvas = CreateNewCanvas();
        }
        CreateSlider(canvas);
    }

    private void CreateSlider(Canvas canvas)
    {
        GameObject sliderObject = new GameObject("WindSlider");
        sliderObject.transform.SetParent(canvas.transform, false);

        slider = sliderObject.AddComponent<Slider>();
        RectTransform rt = sliderObject.GetComponent<RectTransform>();
        rt.sizeDelta = new Vector2(200, 20);
        rt.anchoredPosition = new Vector2(0, -100);
    }

    private Canvas CreateNewCanvas()
    {
        GameObject canvasObject = new GameObject("AutoGeneratedCanvas");
        Canvas canvas = canvasObject.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvasObject.AddComponent<CanvasScaler>();
        canvasObject.AddComponent<GraphicRaycaster>();
        return canvas;
    }
    public void SetPropertyToControl(WindProperty newProperty)
    {
        if (propertyToControl == newProperty)
        {
            Debug.Log("Slider property already set. Skipping update.");
            return; // Avoid unnecessary re-syncs
        }

        // Update the property to control
        propertyToControl = newProperty;

        // Detach the listener to avoid feedback loops
        slider.onValueChanged.RemoveAllListeners();

        // Retrieve and sync the new property's min, max, and current value
        float newValue = 0f;
        switch (propertyToControl)
        {
            case WindProperty.Speed:
                slider.minValue = windSettings.minWindSpeed;
                slider.maxValue = windSettings.maxWindSpeed;
                newValue = Mathf.Clamp(windSettings.GetWindSpeed(), slider.minValue, slider.maxValue);
                break;
            case WindProperty.Turbulence:
                slider.minValue = windSettings.minTurbulence;
                slider.maxValue = windSettings.maxTurbulence;
                newValue = Mathf.Clamp(
                    windSettings.windZone != null ? windSettings.windZone.windTurbulence : windSettings.defaultTurbulence,
                    slider.minValue,
                    slider.maxValue
                );
                break;
            case WindProperty.Interval:
                slider.minValue = 0.1f; // Example range for intervals
                slider.maxValue = 10f;
                newValue = Mathf.Clamp(WindManager.Instance.windChangeInterval, slider.minValue, slider.maxValue);
                break;
            default:
                Debug.LogError($"Invalid property {propertyToControl}");
                return;
        }

        // Set the slider to the new value for the selected property
        slider.SetValueWithoutNotify(newValue);

        // Reattach the listener
        slider.onValueChanged.AddListener(UpdateWindProperty);

        // Sync the slider visually
        //Debug.Log($"Updated Slider: min={slider.minValue}, max={slider.maxValue}, value={newValue}");
    }

}
